### PR TITLE
Update README.md - specify Sierra incompatiblity

### PR DESCRIPTION
**Pull request by MatzFan**

### CODE REVIEW

**Comment by Mystelven** [comment]
+1 ! it was such a disappointment to see the build success and that by moving the Bundle, the same error message from Sierra was appearing...

**Comment by arderyp** [comment]
So, is there some official channel that the GPGTools team is providing status updates on the Sierra incompatibility?  I see this (https://gpgtools.tenderapp.com/discussions/problems/49449-will-not-work-on-macosx-sierra), but no developer updates there as far as I can tell, despite the huge demand.  And issues being private on this project makes transparency here a little tough.  If anyone has any info, or can point me (and others) in the right direction for status updates, I'd greatly appreciate it!

**Comment by lukele** [comment]
Thank you for bringing this to our attention.
We have updated the README and our website accordingly.

**Comment by MatzFan** [comment]
Hope the change can be reverted soon 😄

**Comment by lukele** [comment]
Oh so do we!

**Pull request closed without merging**
